### ISSUE TITLE
create simple-base-schema, simple-base-defaults, simple-base-meta-info

### ISSUE THREAD

**Issue by maany** [WLCG-Lightweight-Sites/simple_grid_site_defaults#4]
Consider the sample site level config file: https://github.com/WLCG-Lightweight-Sites/simple_grid_yaml_compiler/blob/master/tests/resources/complete_config.yaml 

simple-base-schema.yaml must describe the following sections
- schema
- global_variables (the vars section must be renamed to global_variables)
- site_infrastructure
- lightweight_components

```
schema: {type: url(), required: true, use_default: true}
global_variables: {type: list(global_variable), required: false, use_default: false}
site_infrastructure: {type: list(include('node'), required: true, use_default: false}
lightweight_components: {type: list(include('lightweight_component'), required: true, use_default: false}
---
node:
  ...
---
lightweight_component:
  name: {type: str(), required: true, use_default: false}
  ..
  ..
  config: {type: component_repository_schema(), required: true, use_default: false}
```

simple-base-defaults.yaml would look like:
```
simple_base_default_var_schema: &simple_base_default_var_schema http://github.com/WLCG-lightweight-Sites/simple_grid_site_repo/simple-base-schema.yaml
```
simple-base-meta-info.yaml
```
component: simple-base
default_var_prefix: simple_base_default_var
type: schema
version: 1.0
```

**Comment by snehasi** [comment]
Hi @maany, I've been working on the base schema and I was using the linked config file as the reference. It has some undefined aliases for which I couldn't infer the type. For example, [line 60](https://github.com/WLCG-Lightweight-Sites/simple_grid_yaml_compiler/blob/f4f3ff1a13678c3d81719e04291333c7cd9a30e9/tests/resources/complete_config.yaml#L60)
What does it refer to?
I've added the [base schema](https://github.com/snehasi/simple_grid_site_repo/blob/master/site_level_configuration_schema.yaml) on my fork, it doesn't have additional params for validation like required() and defaults() right now.

**Comment by maany** [comment]
@snehasi  hey, yeah that is because of a bug in the compiler we recently discovered. We fixed it recently in the following PR:
https://github.com/WLCG-Lightweight-Sites/simple_grid_yaml_compiler/pull/46
It has been merged into master. If you rebase your local compiler directory, things should work. 
Let me know ;)

**Comment by snehasi** [comment]
Hi Mayank, 
Thanks, I'm validating the output.yaml generated by the compiler with the schema. 
I have to link to the local config file in `component_repo_schema` for defining the config in `lightweight component` of base schema. How will I use multiple files for one validation in Yamale? Should I do the linking via a script instead?

**Comment by maany** [comment]
Hey @snehasi , yes the component_repository_schema()  needs to be replaced by the config-schema.yaml files for the respective component repositories mentioned in the site-level-config-file.yaml (which will be validated by the modified base schema in which the component_repository_schema() has been processed). This change has to be performed by the yaml_compiler. Ideally in a new phase (phase 7). I will be creating an issue for this tomorrow. Feel free to use a temp script for now. We can move that script to phase 7  (new) of the compiler when you work on the issue, once created.

**Comment by maany** [comment]
@snehasi re-opening this issue as in the master branch, we still gotta refactor the base-schema to the format mentioned in the issue description. At present, https://github.com/WLCG-Lightweight-Sites/simple_grid_site_repo/blob/master/simple_base_schema.yaml is still in yamale format.

**Comment by maany** [comment]
Done!
